#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -x "$(command -v bunx)" ]; then
  bunx commitlint --edit ${1}
elif [ -x "$(command -v pnpm)" ]; then
  pnpm exec commitlint --edit ${1}
else
  npx --no -- commitlint --edit ${1}
fi